export { SearchByCar } from './SearchByCar'
export { CarBodyLazy as CarBody } from './CarBody/CarBody.lazy'
export { CarModelLazy as CarModel } from './CarModel/CarModel.lazy'
export { CarBrandLazy as CarBrand } from './CarBrand/CarBrand.lazy'

export { ProductLazy as Product } from './Product/Product.lazy'
export { ProductCategory } from './ProductCategory'
export { AboutLazy as About } from './About/About.lazy'
export { ContactsLazy as Contacts } from './Contacts/Contacts.lazy'
export { Home } from './Home'
